apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: argocd-demo-bucket
  annotations:
    crossplane.io/external-name: argocd-demo-bucket-planectl
spec:
  forProvider:
    region: eu-west-1
  providerConfigRef:
    name: default
  deletionPolicy: Delete
